runtime: java
env: flex

#env_variables:
#  MY_VAR: 'my value'

handlers:
- url: /.*
  script: this field is required, but ignored
#  secure: never

manual_scaling:
  instances: 1

env_variables:
  JAVA_OPTS: >-
    -D.level=trace
